spring:
  application: name=fieldServiceV2

  datasource:
    url: jdbc:mariadb://localhost:3307/fieldService
    username: root
    password: 12345

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update

#  security:
#    user:
#      name: admin
#      password: 123
#      roles: [ ADMIN ]

google:
  maps:
    api:
      key: AIzaSyAsX0jxYtre8VHDZJr4i9myIjwLyyPty48

#
#logging:
#  level:
#    org:
#      springframework:
#        web:
#          servlet:
#            mvc:
#              method:
#                annotation:
#                  RequestMappingHandlerMapping: TRACE


springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui